# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

s = 0
n = 0
top = 4000000
while True:
    if n == 0:
        n1 = 1
        n = n1
    elif n == 1:
        n2 = 2
        n = n2
    else:
        n = n1 + n2
        n1 = n2
        n2 = n

    if n < top:
        if n % 2 == 0:
            s = s + n
    else:
        break


print(s)
